### ISSUE TITLE
card is not supported

### ISSUE THREAD

**Issue by ayoub96anbara** [Tap-Payments/goSellSDK-AndroidX#15]
I have tested the sample example, but I found two problems:
1- Build failed #35, so I have deleted 
   `// implementation 'com.github.Tap-Payments:TapColorsKit-Android:1.0'`
to run the app 
2- the second problem is when I try to enter card number visa 4508750015741019 that I took it from https://www.tap.company/kw/en/developers (Test Card Numbers section) the alert dialog appears to indicate that this card is not supported
![yy](https://user-images.githubusercontent.com/40923656/90813960-48ea6180-e320-11ea-9bb0-acc9002cb2c6.jpg)

**Comment by AhlaamK-tap** [comment]
Hi @ayoub96anbara ,
Seems like you have set ` sdkSession.setCardType(CardType.CREDIT); // ** Optional ** you can pass which cardType[CREDIT/DEBIT] you want.By default it loads all available cards for Merchant.` ,Because of which you are getting this dialog alert.

sdkSession.setCardType(CardType.CREDIT) is an optional field if you set credit or debit it will allow only credit or debit cards and give alert if specified card is not used.

Thank you
