### ISSUE TITLE
Sdk follows device language not app langauge

### ISSUE THREAD

**Issue by amerelsayed1** [Tap-Payments/goSellSDK-AndroidX#23]
i have use these line to set language to arabic 

ThemeObject.getInstance()
            .setAppearanceMode(AppearanceMode.FULLSCREEN_MODE)
            .setSdkLanguage("ar")

and 

GoSellSDK.setLocale("ar")

And sdk forced to follow device language so how to make it follow app language

**Comment by AhlaamK-tap** [comment]
@amerelsayedn1 Please let us know which version of the library are you using ? Ensure to uninstall and re-install app completely.
Since it works fine , irrespective of the device language. If your app language is **ar** above code is correct and if it's english then change it to **en** . If you are using any other language let us know.

Thanks

**Comment by utkarsh19shukla** [comment]
this issue persists Sdk follows the device language, not the app language even after setting the locale to Arabic it uses English 

I am using "GoSellSDK.setLocale("ar")" this method and ".setSdkLanguage("ar")" in theme object
