### ISSUE TITLE
Unable to detect "close" button pressed after selecting Fawry payment method (egp)

### ISSUE THREAD

**Issue by gfran93** [Tap-Payments/goSellSDK-AndroidX#26]
There is not callback method to detect when the operation is finished for this payment method. I need to check if this payment was done using fawry or if the user closed the sdk with a back (or cancel) action.

<img src="https://user-images.githubusercontent.com/5298498/157888342-0d64f480-e935-48b8-a6cd-1d43c103b8fb.png" width="250">

**Comment by AhlaamK-tap** [comment]
Firstly , **Fawry is an asynchronous Payment Method** , which means the payment can be done by the Merchant anytime between 24-48hrs using this code as per his convenience . Also this code will be sent to his mobile/email to be used.
Here **we as SDK just generate a code for them** , which  can be used by user for payment deposit money through Fawry store outlets offline or  online  . Then he gets a paid reciept from Fawry and he shares it with the merchant
 **so our duty only is creating a payment code  in Fawry case** .
Incase if there is **any failure in generating code, it will be notified here** , Otherwise in all cases code is generated. 
Thus there is no callbacks as we dont do any payment .

**Comment by gfran93** [comment]
I completely understand about asynchronous payment method. However, we need to detect if this payment method was selected (hence, this code was generated) or if the sdk was closed by other way: for instance, when the user presses back button.

**Comment by mirland** [comment]
Hi @AhlaamK-tap, can you give us some feedback please. It's blocking our release, so it's important for us

**Comment by AhlaamK-tap** [comment]
Hello @gfran93  @mirland  , 
Will check this with our backend team internally and get back to you.

**Comment by AhlaamK-tap** [comment]
Hi ,We now have a https://github.com/Tap-Payments/goSellSDK-AndroidX/tree/3.15.10#asynchpaymentstarted--callback 
AndroidX - 3.15.10 onwards , which can help in detecting about fawry payments
